# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
logo: "/apple-touch-icon.png"

title: TecSul Instalações Elétricas
email: eletrica.tecsul@gmail.com
description: >-
  TecSul Instalações Elétricas, localizada em Esteio - RS, oferece serviços completos de instalações elétricas, manutenção, automação, instalação de câmeras, motores de portão, venda e instalação de postes, entre outros. Atendemos residências, empresas e indústrias em toda a região metropolitana de Porto Alegre. Soluções seguras, modernas e personalizadas para sua necessidade.

github_username: tecsul-instalacoes-eletricas
minimal_mistakes_skin: contrast

search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /projetos/page:num/
timezone: America/Sao_Paulo

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

#author:   - jekyll-feed
#  name   : "First Lastname"
#  avatar : "/assets/images/bio-photo.jpg"
#  bio    : "My awesome biography constrained to a sentence or two goes here."
#  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

social:
  instagram: https://www.instagram.com/tecsul.istalacoes?igsh=MXZzOHZhbGg2dWdhYw==
  facebook: https://www.facebook.com/share/16EsEzgPMa/

footer:
 links:
   - label: "Instagram"
     icon: "fab fa-fw fa-instagram"
     url: "https://www.instagram.com/tecsul.istalacoes?igsh=MXZzOHZhbGg2dWdhYw=="
   - label: "Facebook"
     icon: "fab fa-fw fa-facebook"
     url: "https://www.facebook.com/share/16EsEzgPMa/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

  collections:
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: false

sass:
  sass_dir: _sass
  style: compressed

remote_theme: "mmistakes/minimal-mistakes@4.26.2"